default: &default
  adapter: postgresql
  database: schedule_api_development
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: schedule_api_development


test:
  <<: *default
  database: schedule_api_test

# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: schedule_api_development

# test:
#   <<: *default
#   database: schedule_api_test


# production:
#   <<: *default
#   database: schedule_api_production
#   username: schedule_api
#   password: <%= ENV['SCHEDULE_API_DATABASE_PASSWORD'] %>
